
name: Command Test
on: [workflow_dispatch, pull_request]

jobs:
  command-test:
    runs-on: self-hosted
    steps:
      - name: Print username
        run: echo The username is $USER
      - name: exec docker ps
        run: docker ps
