name: Meta Check
on: [workflow_dispatch, pull_request]

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeNA/unity-meta-check@v3
    with:
      projectPath: ./game-ci-test